name: flexalert
description: Plateforme d'Alerte d'Épidémie à Abidjan

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
# Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3

  # Navigation
  go_router: ^12.1.3

  # Gestion d'état
  provider: ^6.1.1

  # Carte
  google_maps_flutter: ^2.5.3

  # Graphiques
  fl_chart: ^0.65.0

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Utilitaires
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/